### ISSUE TITLE
Error TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by salshyn** [IBM-Blockchain/fabric-boilerplate#37]
Hi,

I am having trouble with adding a `thing`. Here's what I get in command line:

```
debug:
{ chaincodeID: 'a0ed64f9efff851b8f03b6e3fa28e4822f6bfeb2c16ca1761f3a2754a4fb0tee',
  fcn: 'update_things',
  args:
   [ '11223344',
     { id: '11223344', description: 'Piano Forte' },
     'test' ] }
Error TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at /Users/user/Documents/Work/fabric-boilerplate/node_modules/hfc/lib/hfc.js:2301:40
    at Array.map (native)
    at prepend (/Users/user/Documents/Work/fabric-boilerplate/node_modules/hfc/lib/hfc.js:2301:14)
    at TransactionContext.newInvokeOrQueryTransaction (/Users/user/Documents/Work/fabric-boilerplate/node_modules/hfc/lib/hfc.js:1564:32)
    at /Users/user/Documents/Work/fabric-boilerplate/node_modules/hfc/lib/hfc.js:1019:18
    at /Users/user/Documents/Work/fabric-boilerplate/node_modules/hfc/lib/hfc.js:1179:20
    at TCertGetter.getNextTCert (/Users/user/Documents/Work/fabric-boilerplate/node_modules/hfc/lib/hfc.js:1651:20)
info: POST /api/v1/thing/update 500 2.193 ms - 21
```

This happens in this line:

```
// Invoke the request from the user object.
        var tx = user.invoke(invokeRequest);
```

The debug in the first code shows `invokeRequest`, after that it fails.

**Comment by salshyn** [comment]
Please nevermind the issue. This was due to incorrect passing of a parameter.
